config/routes.rb
SeventhfireApp::Application.routes.draw do
  resources :locations

  resources :wildfires do
    collection do
      get :search
    end
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :wildfire

	## SCOPES ##   #if argument being passed then use method, if not then use scope
	# scope :georgia, -> { where(state: "GA" OR state: "Georgia")}
	# scope :with_specialty, ->(specialty) { where('specialty = ?', specialty) }


end

app/models/wildfire.rb
class Wildfire < ActiveRecord::Base

	has_many :locations

	## SCOPES ##   #if argument being passed then use method, if not then use scope
	scope :still_burning, -> { where(currently_active: true)}
	scope :not_burning, -> { where(currently_active: false)}
	# scope :with_specialty, ->(specialty) { where('specialty = ?', specialty) }

	def self.with_city(city)
		where('locations.city = ?', city)
	end

	def self.with_state(state)
		where('locations.state = ?', state)
	end

	def self.search(params)
		description = params[:description]
		state = params[:state]
		city = params[:city]

		search = Wildfire.all



		if params[:city].present?
			search = search.with_city(city)
		end

		if params[:state].present?
			search = search.with_state(state)
		end

		if params[:current] == "Yes"
			search = search.still_burning
		elsif params[:current] == "No"
			search = search.not_burning
		end

		if params[:description].present?
			search = search.where('description LIKE ?', "%#{description}%")
			# search = joins(:locations).where('description LIKE ?', "%#{description}%")
		end

		# if name.present?
		# 	# search = search.where('patients.name LIKE ?', "%#{name}%")
		# 	search = joins(:patients).where('patients.name LIKE ?', "%#{name}%")
		# end

		search

		# with_specialty(specialty).where('name LIKE ?', "%#{name}%")
	end

	# def self.search(query)
 #  	Wildfire.joins(:locations).where("locations.wildfire_id like ? OR locations.state like ? OR locations.city like ? OR area_burned like ? OR description like ?",  "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%")
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:city, :state, :wildfire_id)
    end
end

app/controllers/wildfires_controller.rb
class WildfiresController < ApplicationController
  before_action :set_wildfire, only: [:show, :edit, :update, :destroy]

  # GET /wildfires
  # GET /wildfires.json
  def index
    @wildfires = Wildfire.all
  end

  # GET /wildfires/1
  # GET /wildfires/1.json
  def show
  end

  # GET /wildfires/new
  def new
    @wildfire = Wildfire.new
  end

  # GET /wildfires/1/edit
  def edit
  end

  # POST /wildfires
  # POST /wildfires.json
  def create
    @wildfire = Wildfire.new(wildfire_params)

    respond_to do |format|
      if @wildfire.save
        format.html { redirect_to @wildfire, notice: 'Wildfire was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wildfire }
      else
        format.html { render action: 'new' }
        format.json { render json: @wildfire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wildfires/1
  # PATCH/PUT /wildfires/1.json
  def search
    respond_to do |format|
      if @wildfire.search(wildfire_params)
        format.html { redirect_to @wildfire, notice: 'Wildfire was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wildfire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wildfires/1
  # DELETE /wildfires/1.json
  def destroy
    @wildfire.destroy
    respond_to do |format|
      format.html { redirect_to wildfires_url }
      format.json { head :no_content }
    end
  end

  # GET "/wildfires/search"
  def search
    @wildfires = Wildfire.search(params[:search])
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_wildfire
    @wildfire = Wildfire.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wildfire_params
    params.require(:wildfire).permit!
  end
end

#   def index
#     @wildfires = Wildfire.all
#   end

#   def new
#     @new_wildfire = Wildfire.new
#   end

#   def create
#     @new_wildfire = Wildfire.new(wildfire_params)
#     if @new_wildfire.save
#       redirect_to wildfires_path # "/wildfires"
#     else
#       redirect_to new_wildfire_path
#     end
#   end

#   # PATCH "/wildfires/:id/change_burning"
#   def change_burning
#     @wildfire = Wildfire.find(params[:id])
#     if @wildfire.currently_active
#       val = false
#     else
#       val = true
#     end
#     @wildfire.update_attributes(:currently_active => val)
#     redirect_to wildfires_path
#   end

#   # GET "/wildfires/search"
#   def search
#     @wildfires = Wildfire.search(params[:search])
    
#   end

#   private

#   def wildfire_params
#     params.require(:wildfire).permit!
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/wildfires_helper.rb
module WildfiresHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Wildfires
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield

app/views/locations/_form.html.haml
= form_for(@location) do |f|
  - if @location.errors.any?
    #error_explanation
      %h2
        = pluralize(@location.errors.count, "error")
        prohibited this location from being saved:
      %ul
        - @location.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :city
    %br/
    = f.text_field :city
  .field
    = f.label :state
    %br/
    = f.text_field :state
  .field
    = f.label :wildfire_id
    %br/
    = f.number_field :wildfire_id
  .actions
    = f.submit

app/views/locations/edit.html.haml
%h1 Editing location
= render 'form'
= link_to 'Show', @location
|
\#{link_to 'Back', locations_path}

app/views/locations/index.html.haml
%h1 Listing locations
%table
  %thead
    %tr
      %th City
      %th State
      %th Wildfire
      %th
      %th
      %th
  %tbody
    - @locations.each do |location|
      %tr
        %td= location.city
        %td= location.state
        %td= location.wildfire_id
        %td= link_to 'Show', location
        %td= link_to 'Edit', edit_location_path(location)
        %td= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Location', new_location_path

app/views/locations/new.html.haml
%h1 New location
= render 'form'
= link_to 'Back', locations_path

app/views/locations/show.html.haml
%p#notice= notice
%p
  %strong City:
  = @location.city
%p
  %strong State:
  = @location.state
%p
  %strong Wildfire:
  = @location.wildfire_id
= link_to 'Edit', edit_location_path(@location)
|
\#{link_to 'Back', locations_path}

app/views/wildfires/_form.html.haml
= form_for(@wildfire) do |f|
  - if @wildfire.errors.any?
    #error_explanation
      %h2
        = pluralize(@wildfire.errors.count, "error")
        prohibited this wildfire from being saved:
      %ul
        - @wildfire.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :start_date
    %br/
    = f.date_select :start_date 
  .field
    = f.label :description
    %br/
    = f.text_field :description
  .field
    = f.label :area_burned
    %br/
    = f.number_field :area_burned
  .field
    = f.label :fatalities
    %br/
    = f.number_field :fatalities
  .field
    = f.label 'Still active? (Put "true" or "false")'
    = f.text_field :currently_active
  .actions
    = f.submit

app/views/wildfires/edit.html.haml
%h1 Editing wildfire
= render 'form'
= link_to 'Show', @wildfire
|
\#{link_to 'Back', wildfires_path}

app/views/wildfires/index.html.haml
= form_tag(search_wildfires_path, :method => "get", id: "search-form") do
  = label_tag "Description"
  = text_field_tag 'search[description]'
  %br
  = label_tag "City"
  - x = Location.pluck(:city)
  = select_tag 'search[city]', options_for_select(x), include_blank: true
  %br
  = label_tag "Still active?"
  = select_tag "search[current]", options_for_select(["Yes", "No"]), include_blank: true
  %br
  = submit_tag "SEARCH"

/ = form_tag(wildfires_path, :method => "get", id: "search-form") do
/   = select_tag "wildfire_id", options_for_select(['---', 'State', 'Description','Area Burned'])
/   = text_field_tag :search, params[:search], placeholder: "Search Wildfires"
/   = submit_tag "Search"  




%h1 List of wildfires
%table
  %thead
    %tr
      %th Id
      %th Start date
      %th Description
      %th Area burned
      %th Fatalities
      %th
      %th
      %th
  %tbody
    - @wildfires.each do |wildfire|
      %tr
        %td= wildfire.id
        %td= wildfire.start_date  
        %td= wildfire.description
        %td= wildfire.area_burned
        %td= wildfire.fatalities
        %td= link_to 'Show', wildfire
        %td= link_to 'Edit', edit_wildfire_path(wildfire)
        %td= link_to 'Destroy', wildfire, method: :delete, data: { confirm: 'Are you sure?' }
%br

= button_to 'Add New Wildfire', new_wildfire_path, method: "get"

app/views/wildfires/new.html.haml
%h1 New wildfire
= render 'form'
= link_to 'Back', wildfires_path

app/views/wildfires/search.html.haml
- @wildfires.each do |w|
	Start date:
	= w.start_date
	%br
	Description:
	= w.description
	%br
	Currently active?:
	= w.currently_active
	%br
	%br

app/views/wildfires/show.html.haml
%p#notice= notice
%p
  %strong Start date:
  = @wildfire.start_date
%p
  %strong Description:
  = @wildfire.description
%p
  %strong Area burned:
  = @wildfire.area_burned
%p
  %strong Fatalities:
  = @wildfire.fatalities
%p
  %strong Still active?:
  = @wildfire.currently_active
= link_to 'Edit', edit_wildfire_path(@wildfire)
|
\#{link_to 'Back', wildfires_path}